CREATE TABLE Usuario (
idUsuario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
NombreApellido VARCHAR(100) NOT NULL,
Contrasena VARCHAR(100) NOT NULL,
Correo VARCHAR(100) NOT NULL
);

CREATE TABLE Ruta (
idRuta INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR(100) NOT NULL,
Horarios VARCHAR(1000) NOT NULL,
Cordenadas VARCHAR(100) NOT NULL,
CiudadDestino VARCHAR(100) NOT NULL,
CiudadOrigen VARCHAR(100) NOT NULL
);

CREATE TABLE Comentario (
idComentario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
ComentarioUsuario VARCHAR(280) NOT NULL,
CLike INTEGER,
Dislike INTEGER,
fkUsuario INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY(fkUsuario) REFERENCES Usuario(idUsuario)
);

CREATE TABLE RutaUsuario(
idRutaUsuario INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
fkRuta INTEGER NOT NULL,
fkUsuario INTEGER NOT NULL,
CONSTRAINT FOREIGN KEY(fkRuta) REFERENCES Ruta(idRuta),
CONSTRAINT FOREIGN KEY(fkUsuario) REFERENCES Usuario(idUsuario)
);
SELECT * FROM streaming.usuario;


SELECT * FROM streaming.ruta;

INSERT INTO Ruta (Nombre, Horarios, Cordenadas, CiudadDestino, CiudadOrigen)
VALUES ('Ruta1', '5:15AM - 10:00PM', '4.864909639282648, -74.05120513489219' , 'Chía' , 'Bogota' );

SELECT * FROM streaming.ruta;

ALTER TABLE comentario DROP COLUMN  CLike;
ALTER TABLE comentario DROP COLUMN  Dislike;






